version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
        - .env.local
    image: wexchange_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - wexchange_network

  postgres:
    image: postgres:latest
    container_name: wexchange_postgres
    environment:
      POSTGRES_PASSWORD: SomeSecuredPassword
      POSTGRES_DB: wexchange
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - wexchange_network

networks:
  wexchange_network:
