version: '3.8'

services:
  app:
    build: .
    image: wexchange_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - wexchange_network
    environment:
      DATABASE_POSTGRES_USERNAME: postgres
      DATABASE_POSTGRES_PASSWORD: YourSecurePassword
      DATABASE_POSTGRES_URL: jdbc:postgresql://postgres:5432/wexchange

  postgres:
    image: postgres:latest
    container_name: wexchange_postgres
    environment:
      POSTGRES_PASSWORD: YourSecurePassword
      POSTGRES_DB: wexchange
    volumes:
      - ./db-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - wexchange_network

networks:
  wexchange_network:
