version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: wexchange_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: wexchange
    # ports:
    #   - "5432:5432"
    networks:
      - wexchange_network
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U postgres"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

networks:
  wexchange_network:
    driver: bridge

# volumes:
#   postgres_data:
#     driver: local