version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: wexchange_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: wexchange
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - wexchange_network

networks:
  wexchange_network:
    driver: bridge
